variables:
  COMPILER: clang
  CCACHE_DIR: $(Pipeline.Workspace)/ccache

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- bash: |
    sudo apt-get install ccache -y
    echo "##vso[task.prependpath]/usr/lib/ccache"
  displayName: Install ccache and update PATH to use linked versions of gcc, cc, etc

- task: CacheBeta@0
  inputs:
    key: ccache | $(Agent.OS)
    path: $(CCACHE_DIR)
  displayName: ccache

- bash: |
    docker pull rpcs3/rpcs3-travis-trusty:1.1
    docker run                      \
      -v $(pwd):/rpcs3              \
      -v $CCACHE_DIR:/root/.ccache  \
      rpcs3/rpcs3-travis-trusty:1.1 \
      /bin/bash -ex /rpcs3/.travis/build-linux.bash
    ls -al build/bin
    displayName: Fetch and build with Docker

- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: '**/$(BuildConfiguration)/**/?(rpcs3)'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: drop
